# Generated by Django 5.2.4 on 2025-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NajotTalim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kurs_nomi', models.CharField(max_length=100)),
                ('Kurs_turi', models.CharField(max_length=100)),
                ('Kurs_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Kurs_muddati', models.CharField(max_length=50)),
                ('Darslar_soni', models.IntegerField()),
                ('Darslar_soati', models.IntegerField()),
                ('Kurs_haqida', models.TextField()),
            ],
        ),
    ]
